---
# tasks file for webserver
- name: install apache
  yum:
    name: httpd
    state: present

- name: create files with hostnames
  template:
    src: "vm.html.j2"
    dest: "/var/www/html/{{ item }}"
  loop: "{{ apache_files }}"
  vars:
    hostname: "{{ inventory_hostname }}"

- name: start apache
  systemd:
    name: httpd
    state: started
    enabled: "{{ apache_autostart_on_boot }}"
