---
# tasks file for users
- name: Add cloudadmins group
  group:
    name: cloudadmins
    state: present

- name: Add users
  user:
    name: "{{ item.name }}"
    groups: "{{ item.groups }}"
    shell: /bin/bash
    createhome: yes
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: "{{ item.ssh_key_file | default('~/.ssh/id_rsa') }}"
    ssh_key_type: rsa
  loop: "{{ users }}"

- name: Distribute SSH keys
  when: item.ssh_key_file is defined
  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ lookup('file', item.ssh_key_file + '.pub') }}"
  loop: "{{ users }}"
